### ISSUE TITLE
About updates on this package

### ISSUE THREAD

**Issue by nelson777** [flathub/org.eclipse.Javascript#9]
Hello, 

I use this flatpak package for some time and I'm interested about how long the updates will take. I know that WWD was updated to higher version in 2022-05-29 and 2022-07-07. Could you inform when we will have a newer package ? Thanks. 

I also saw that user @akurtakov has fork to it that is 2 commits ahead from the main project. It's updated to the last version ? if yes how do I use it ? 

Are you needing help ? I don't have any experience on creating Flatpak packages, but if it's a task that doesn't take too long maybe I could help. If that's the case please share a link to the documentation where I can educate myself on how I could help you.

**Comment by akurtakov** [comment]
Update in most cases is trivial and help is more than welcome as I'm quite loaded with upstream work. I'll handle it now but if you can look at the change and provide it next time it will be *very appreciated*.

**Comment by nelson777** [comment]
I took a look at the files... Am I missing something or the change it's only 2 files ? org.eclipse.Javascript.json and org.eclipse.Javascript.metainfo.xml ? which are very small by the way.

If it's only that I surely can provide them next time. I use Eclipse daily and like to keep up with updates as soon as they arrive.

**Comment by nelson777** [comment]
I took a look further and see that WWD doesn't provide sha1 and sha512 hashes. Can I just calculate them using any random tool or there is a "proper way" ?

**Comment by akurtakov** [comment]
It's only change to these 2 files and you can download and calculate the sha with any tool.

**Comment by nelson777** [comment]
Cool... very easy. Next one leave it to me. I'll make a PR. :)

**Comment by akurtakov** [comment]
Thanks!

**Comment by nelson777** [comment]
As promised made a PR on the latest update. But I got some doubts, please check PR text. Thanks.
